[package]
name = "abnf"
version = "0.1.0"
authors = ["Martin Hoffmann <hn@nvnc.de>"]

[dependencies]
futures    = "0.1.10"
#tokio-core = "0.1.4"
tokio-core = { git = "https://github.com/tokio-rs/tokio-core.git" }
